// Mozilla User Preferences

// DO NOT EDIT THIS FILE.
//
// If you make changes to this file while the application is running,
// the changes will be overwritten when the application exits.
//
// To change a preference value, you can either:
// - modify it via the UI (e.g. via about:config in the browser); or
// - set it within a user.js file in your profile.

user_pref("app.update.lastUpdateTime.addon-background-update-timer", 1654092110);
user_pref("app.update.lastUpdateTime.browser-cleanup-thumbnails", 1654091750);
user_pref("app.update.lastUpdateTime.search-engine-update-timer", 1654091870);
user_pref("app.update.lastUpdateTime.services-settings-poll-changes", 1654091990);
user_pref("app.update.lastUpdateTime.xpi-signature-verification", 1654092230);
user_pref("browser.bookmarks.addedImportButton", true);
user_pref("browser.bookmarks.restore_default_bookmarks", false);
user_pref("browser.contentblocking.category", "strict");
user_pref("browser.download.autohideButton", true);
user_pref("browser.download.viewableInternally.typeWasRegistered.avif", true);
user_pref("browser.download.viewableInternally.typeWasRegistered.webp", true);
user_pref("browser.migration.version", 125);
user_pref("browser.newtabpage.activity-stream.impressionId", "{dcd4aba0-f73d-4f75-9ddf-8d55f3dfd089}");
user_pref("browser.newtabpage.enabled", false);
user_pref("browser.newtabpage.storageVersion", 1);
user_pref("browser.pageActions.persistedActions", "{\"ids\":[\"bookmark\",\"canvasblocker_kkapsner_de\"],\"idsInUrlbar\":[\"canvasblocker_kkapsner_de\",\"bookmark\"],\"idsInUrlbarPreProton\":[],\"version\":1}");
user_pref("browser.pagethumbnails.storage_version", 3);
user_pref("browser.policies.applied", true);
user_pref("browser.policies.runOncePerModification.addSearchEngines", "/S92rzfUdA8IqLNkEq93Ow==");
user_pref("browser.policies.runOncePerModification.extensionsInstall", "[\"https://addons.mozilla.org/firefox/downloads/file/3933192/ublock_origin-1.42.4-an+fx.xpi\"]");
user_pref("browser.policies.runOncePerModification.extensionsUninstall", "[\"google@search.mozilla.org\",\"bing@search.mozilla.org\",\"amazondotcom@search.mozilla.org\",\"ebay@search.mozilla.org\",\"twitter@search.mozilla.org\"]");
user_pref("browser.policies.runOncePerModification.removeSearchEngines", "[\"Google\",\"Bing\",\"Amazon.com\",\"eBay\",\"Twitter\"]");
user_pref("browser.policies.runOncePerModification.setDefaultSearchEngine", "DuckDuckGo");
user_pref("browser.proton.toolbar.version", 3);
user_pref("browser.safebrowsing.appRepURL", "");
user_pref("browser.safebrowsing.provider.mozilla.lastupdatetime", "1654091723039");
user_pref("browser.safebrowsing.provider.mozilla.nextupdatetime", "1654113323039");
user_pref("browser.shell.mostRecentDateSetAsDefault", "1654092894");
user_pref("browser.startup.couldRestoreSession.count", 1);
user_pref("browser.startup.lastColdStartupCheck", 1654092894);
user_pref("browser.theme.toolbar-theme", 0);
user_pref("browser.toolbars.bookmarks.visibility", "never");
user_pref("browser.uiCustomization.state", "{\"placements\":{\"widget-overflow-fixed-list\":[],\"nav-bar\":[\"back-button\",\"forward-button\",\"stop-reload-button\",\"urlbar-container\",\"save-to-pocket-button\",\"downloads-button\",\"fxa-toolbar-menu-button\",\"canvasblocker_kkapsner_de-browser-action\",\"https-everywhere_eff_org-browser-action\",\"jid1-mnnxcxisbpnsxq_jetpack-browser-action\",\"ublock0_raymondhill_net-browser-action\",\"_446900e4-71c2-419f-a6a7-df9c091e268b_-browser-action\",\"addon_darkreader_org-browser-action\"],\"toolbar-menubar\":[\"menubar-items\"],\"TabsToolbar\":[\"tabbrowser-tabs\",\"new-tab-button\",\"alltabs-button\"],\"PersonalToolbar\":[\"import-button\",\"personal-bookmarks\"]},\"seen\":[\"canvasblocker_kkapsner_de-browser-action\",\"https-everywhere_eff_org-browser-action\",\"jid1-mnnxcxisbpnsxq_jetpack-browser-action\",\"umatrix_raymondhill_net-browser-action\",\"ublock0_raymondhill_net-browser-action\",\"developer-button\",\"_446900e4-71c2-419f-a6a7-df9c091e268b_-browser-action\",\"addon_darkreader_org-browser-action\"],\"dirtyAreaCache\":[\"nav-bar\",\"PersonalToolbar\",\"toolbar-menubar\",\"TabsToolbar\"],\"currentVersion\":17,\"newElementCount\":3}");
user_pref("browser.urlbar.shortcuts.bookmarks", false);
user_pref("browser.urlbar.shortcuts.history", false);
user_pref("browser.urlbar.shortcuts.tabs", false);
user_pref("devtools.webextensions.https-everywhere@eff.org.enabled", true);
user_pref("distribution.iniFile.exists.appversion", "100.0.2");
user_pref("distribution.iniFile.exists.value", true);
user_pref("distribution.io.gitlab.librewolf-community.bookmarksProcessed", true);
user_pref("dom.battery.enabled", false);
user_pref("dom.forms.autocomplete.formautofill", true);
user_pref("dom.indexedDB.enabled", false);
user_pref("dom.push.userAgentID", "99cc54b4f7a647cebd1fa4364f22475a");
user_pref("dom.security.https_only_mode_ever_enabled", true);
user_pref("dom.storage.enabled", false);
user_pref("extensions.CanvasBlocker@kkapsner.de.whiteList", "");
user_pref("extensions.activeThemeID", "{b743f56d-1cc1-4048-8ba6-f9c2ab7aa54d}");
user_pref("extensions.autoDisableScopes", 14);
user_pref("extensions.blocklist.pingCountVersion", 0);
user_pref("extensions.databaseSchema", 35);
user_pref("extensions.lastAppBuildId", "20220521145420");
user_pref("extensions.lastAppVersion", "100.0.2");
user_pref("extensions.lastPlatformVersion", "100.0.2");
user_pref("extensions.pendingOperations", true);
user_pref("extensions.pictureinpicture.enable_picture_in_picture_overrides", true);
user_pref("extensions.systemAddonSet", "{\"schema\":1,\"addons\":{}}");
user_pref("extensions.ui.dictionary.hidden", true);
user_pref("extensions.ui.extension.hidden", false);
user_pref("extensions.ui.lastCategory", "addons://list/extension");
user_pref("extensions.ui.locale.hidden", true);
user_pref("extensions.ui.sitepermission.hidden", true);
user_pref("extensions.ui.theme.hidden", false);
user_pref("extensions.webcompat.enable_shims", true);
user_pref("extensions.webcompat.perform_injections", true);
user_pref("extensions.webcompat.perform_ua_overrides", true);
user_pref("extensions.webextensions.ExtensionStorageIDB.migrated.CanvasBlocker@kkapsner.de", true);
user_pref("extensions.webextensions.ExtensionStorageIDB.migrated.addon@darkreader.org", true);
user_pref("extensions.webextensions.ExtensionStorageIDB.migrated.extension@tabliss.io", true);
user_pref("extensions.webextensions.ExtensionStorageIDB.migrated.https-everywhere@eff.org", true);
user_pref("extensions.webextensions.ExtensionStorageIDB.migrated.jid1-MnnxcxisBPnSXQ@jetpack", true);
user_pref("extensions.webextensions.ExtensionStorageIDB.migrated.screenshots@mozilla.org", true);
user_pref("extensions.webextensions.ExtensionStorageIDB.migrated.uBlock0@raymondhill.net", true);
user_pref("extensions.webextensions.uuids", "{\"CanvasBlocker@kkapsner.de\":\"15e2aee7-59a9-4781-bad1-9632de7ef716\",\"https-everywhere@eff.org\":\"55cfc286-f20c-436c-aaff-7207a532ff82\",\"uBlock0@raymondhill.net\":\"8a6265b9-da59-47e4-8eae-9ca7fa43e907\",\"jid1-MnnxcxisBPnSXQ@jetpack\":\"3cff3bd8-ac57-4ba3-a23e-f623068592f5\",\"formautofill@mozilla.org\":\"62449bf5-8ddd-49fc-8241-e594d1e7095c\",\"pictureinpicture@mozilla.org\":\"7f119464-3934-47af-8f92-1b3183b0df53\",\"screenshots@mozilla.org\":\"568e771d-ab45-408e-9b08-e8e45ac9a83b\",\"webcompat@mozilla.org\":\"c6f21122-4f7a-445e-bae3-49cc7bbd95c4\",\"default-theme@mozilla.org\":\"0e23ff42-128d-4586-84f9-d1807d0bdfb2\",\"addons-search-detection@mozilla.com\":\"c906b140-66ad-470c-86fd-7f5fa910fef0\",\"wikipedia@search.mozilla.org\":\"1a1283a8-6231-4ebb-8cad-6283a7596938\",\"ddg@search.mozilla.org\":\"a7777046-8ea3-47dd-834d-a8d909deb07c\",\"{b743f56d-1cc1-4048-8ba6-f9c2ab7aa54d}\":\"af4afed7-6e0b-4a55-a4bf-1ffa7ca5948d\",\"extension@tabliss.io\":\"f62f0e07-2a24-4c65-883f-0cf7ff260364\",\"addon@darkreader.org\":\"03b77c2a-2ea5-4c21-b71f-cee6b318f69a\"}");
user_pref("fission.experiment.max-origins.last-disqualified", 0);
user_pref("fission.experiment.max-origins.last-qualified", 1654091722);
user_pref("fission.experiment.max-origins.qualified", true);
user_pref("gecko.handlerService.defaultHandlersVersion", 1);
user_pref("gfx.blacklist.webrender", 4);
user_pref("gfx.blacklist.webrender.failureid", "FEATURE_FAILURE_DDX_INTEL");
user_pref("intl.accept_languages", "en-US, en");
user_pref("javascript.use_us_english_locale", true);
user_pref("media.gmp-manager.buildID", "20220521145420");
user_pref("media.gmp-manager.lastCheck", 1654093271);
user_pref("media.gmp.storage.version.observed", 1);
user_pref("media.navigator.enabled", false);
user_pref("media.peerconnection.enabled", false);
user_pref("media.video_stats.enabled", false);
user_pref("network.http.referer.disallowCrossSiteRelaxingDefault.top_navigation", true);
user_pref("network.http.referer.spoofSource", true);
user_pref("pdfjs.enabledCache.state", true);
user_pref("pdfjs.migrationVersion", 2);
user_pref("privacy.annotate_channels.strict_list.enabled", true);
user_pref("privacy.donottrackheader.enabled", true);
user_pref("privacy.donottrackheader.value", 1);
user_pref("privacy.history.custom", true);
user_pref("privacy.partition.network_state.ocsp_cache", true);
user_pref("privacy.sanitize.pending", "[{\"id\":\"shutdown\",\"itemsToClear\":[\"cache\",\"cookies\",\"offlineApps\",\"history\",\"formdata\",\"downloads\",\"sessions\"],\"options\":{}},{\"id\":\"newtab-container\",\"itemsToClear\":[],\"options\":{}}]");
user_pref("privacy.trackingprotection.enabled", true);
user_pref("privacy.trackingprotection.socialtracking.enabled", true);
user_pref("privacy.userContext.extension", "CanvasBlocker@kkapsner.de");
user_pref("security.sandbox.content.tempDirSuffix", "c26ac824-11b5-46d6-959e-80a4a1682b5b");
user_pref("services.sync.engine.addresses.available", true);
user_pref("toolkit.startup.last_success", 1654092893);
user_pref("toolkit.telemetry.cachedClientID", "7bac46b9-9c52-48bf-b905-20e1f3e325a0");
