// Mozilla User Preferences

// DO NOT EDIT THIS FILE.
//
// If you make changes to this file while the application is running,
// the changes will be overwritten when the application exits.
//
// To change a preference value, you can either:
// - modify it via the UI (e.g. via about:config in the browser); or
// - set it within a user.js file in your profile.

user_pref("app.update.lastUpdateTime.addon-background-update-timer", 1652375326);
user_pref("app.update.lastUpdateTime.browser-cleanup-thumbnails", 1652374966);
user_pref("app.update.lastUpdateTime.search-engine-update-timer", 1652375086);
user_pref("app.update.lastUpdateTime.services-settings-poll-changes", 1652375206);
user_pref("app.update.lastUpdateTime.xpi-signature-verification", 1652375446);
user_pref("autoadmin.global_config_url", "file:///home/tobias/.librewolf/librewolf.overrides.cfg");
user_pref("browser.bookmarks.addedImportButton", true);
user_pref("browser.bookmarks.restore_default_bookmarks", false);
user_pref("browser.contentblocking.category", "custom");
user_pref("browser.download.panel.shown", true);
user_pref("browser.download.viewableInternally.typeWasRegistered.avif", true);
user_pref("browser.download.viewableInternally.typeWasRegistered.svg", true);
user_pref("browser.download.viewableInternally.typeWasRegistered.webp", true);
user_pref("browser.download.viewableInternally.typeWasRegistered.xml", true);
user_pref("browser.migration.version", 122);
user_pref("browser.newtab.extensionControlled", true);
user_pref("browser.newtab.privateAllowed", true);
user_pref("browser.newtabpage.activity-stream.impressionId", "{fac6ce1f-ac6f-4d94-8d83-65cf5e54246b}");
user_pref("browser.newtabpage.storageVersion", 1);
user_pref("browser.pageActions.persistedActions", "{\"ids\":[\"bookmark\",\"canvasblocker_kkapsner_de\"],\"idsInUrlbar\":[\"canvasblocker_kkapsner_de\",\"bookmark\"],\"idsInUrlbarPreProton\":[],\"version\":1}");
user_pref("browser.pagethumbnails.storage_version", 3);
user_pref("browser.policies.applied", true);
user_pref("browser.policies.runOncePerModification.addSearchEngines", "/S92rzfUdA8IqLNkEq93Ow==");
user_pref("browser.policies.runOncePerModification.extensionsUninstall", "[\"google@search.mozilla.org\",\"bing@search.mozilla.org\",\"amazondotcom@search.mozilla.org\",\"ebay@search.mozilla.org\",\"twitter@search.mozilla.org\"]");
user_pref("browser.policies.runOncePerModification.removeSearchEngines", "[\"Google\",\"Bing\",\"Amazon.com\",\"eBay\",\"Twitter\"]");
user_pref("browser.policies.runOncePerModification.setDefaultSearchEngine", "DuckDuckGo");
user_pref("browser.proton.toolbar.version", 3);
user_pref("browser.safebrowsing.provider.mozilla.lastupdatetime", "1652374890534");
user_pref("browser.safebrowsing.provider.mozilla.nextupdatetime", "1652396490534");
user_pref("browser.shell.checkDefaultBrowser", true);
user_pref("browser.startup.couldRestoreSession.count", 1);
user_pref("browser.startup.homepage", "moz-extension://ccf74df9-8299-488e-ae58-946603fd20ce/index.html");
user_pref("browser.startup.homepage_override.extensionControlled", true);
user_pref("browser.startup.homepage_override.privateAllowed", true);
user_pref("browser.startup.lastColdStartupCheck", 1652374937);
user_pref("browser.theme.toolbar-theme", 0);
user_pref("browser.toolbars.bookmarks.visibility", "never");
user_pref("browser.uiCustomization.state", "{\"placements\":{\"widget-overflow-fixed-list\":[],\"nav-bar\":[\"back-button\",\"forward-button\",\"stop-reload-button\",\"urlbar-container\",\"save-to-pocket-button\",\"fxa-toolbar-menu-button\",\"ublock0_raymondhill_net-browser-action\",\"_446900e4-71c2-419f-a6a7-df9c091e268b_-browser-action\",\"https-everywhere_eff_org-browser-action\",\"jid1-mnnxcxisbpnsxq_jetpack-browser-action\",\"canvasblocker_kkapsner_de-browser-action\"],\"toolbar-menubar\":[\"menubar-items\"],\"TabsToolbar\":[\"tabbrowser-tabs\",\"new-tab-button\",\"alltabs-button\"],\"PersonalToolbar\":[\"import-button\",\"personal-bookmarks\"]},\"seen\":[\"developer-button\",\"ublock0_raymondhill_net-browser-action\",\"_446900e4-71c2-419f-a6a7-df9c091e268b_-browser-action\",\"https-everywhere_eff_org-browser-action\",\"jid1-mnnxcxisbpnsxq_jetpack-browser-action\",\"canvasblocker_kkapsner_de-browser-action\",\"addon_darkreader_org-browser-action\",\"_5b1a796b-231a-4ad1-84ff-918db0818207_-browser-action\"],\"dirtyAreaCache\":[\"nav-bar\",\"PersonalToolbar\",\"toolbar-menubar\",\"TabsToolbar\"],\"currentVersion\":17,\"newElementCount\":3}");
user_pref("browser.urlbar.placeholderName", "Wikipedia (en)");
user_pref("browser.urlbar.shortcuts.bookmarks", false);
user_pref("browser.urlbar.shortcuts.history", false);
user_pref("browser.urlbar.shortcuts.tabs", false);
user_pref("browser.urlbar.suggest.bookmark", false);
user_pref("browser.urlbar.suggest.engines", false);
user_pref("browser.urlbar.suggest.history", false);
user_pref("browser.urlbar.suggest.openpage", false);
user_pref("browser.urlbar.suggest.topsites", false);
user_pref("distribution.iniFile.exists.appversion", "97.0");
user_pref("distribution.iniFile.exists.value", true);
user_pref("distribution.io.gitlab.librewolf-community.bookmarksProcessed", true);
user_pref("dom.push.userAgentID", "ddb1a5a2b82f4afa94c9cbf551651724");
user_pref("dom.security.https_only_mode_ever_enabled", true);
user_pref("extensions.activeThemeID", "{7c7f5097-d453-4951-8638-d1055726a76b}");
user_pref("extensions.blocklist.pingCountVersion", 0);
user_pref("extensions.databaseSchema", 35);
user_pref("extensions.lastAppBuildId", "20220210135346");
user_pref("extensions.lastAppVersion", "97.0");
user_pref("extensions.lastPlatformVersion", "97.0");
user_pref("extensions.pendingOperations", false);
user_pref("extensions.pictureinpicture.enable_picture_in_picture_overrides", true);
user_pref("extensions.systemAddonSet", "{\"schema\":1,\"addons\":{}}");
user_pref("extensions.ui.dictionary.hidden", true);
user_pref("extensions.ui.extension.hidden", false);
user_pref("extensions.ui.lastCategory", "addons://list/extension");
user_pref("extensions.ui.locale.hidden", true);
user_pref("extensions.ui.sitepermission.hidden", true);
user_pref("extensions.ui.theme.hidden", false);
user_pref("extensions.webcompat.enable_shims", true);
user_pref("extensions.webcompat.perform_injections", true);
user_pref("extensions.webcompat.perform_ua_overrides", true);
user_pref("extensions.webextensions.ExtensionStorageIDB.migrated.CanvasBlocker@kkapsner.de", true);
user_pref("extensions.webextensions.ExtensionStorageIDB.migrated.addon@darkreader.org", true);
user_pref("extensions.webextensions.ExtensionStorageIDB.migrated.extension@tabliss.io", true);
user_pref("extensions.webextensions.ExtensionStorageIDB.migrated.https-everywhere@eff.org", true);
user_pref("extensions.webextensions.ExtensionStorageIDB.migrated.jid1-MnnxcxisBPnSXQ@jetpack", true);
user_pref("extensions.webextensions.ExtensionStorageIDB.migrated.screenshots@mozilla.org", true);
user_pref("extensions.webextensions.ExtensionStorageIDB.migrated.uBlock0@raymondhill.net", true);
user_pref("extensions.webextensions.ExtensionStorageIDB.migrated.{446900e4-71c2-419f-a6a7-df9c091e268b}", true);
user_pref("extensions.webextensions.ExtensionStorageIDB.migrated.{5b1a796b-231a-4ad1-84ff-918db0818207}", true);
user_pref("extensions.webextensions.uuids", "{\"formautofill@mozilla.org\":\"532c105a-d60c-46ec-8836-132634d9d23b\",\"pictureinpicture@mozilla.org\":\"678dadd7-fcc1-49c5-a33f-a4cb52716479\",\"screenshots@mozilla.org\":\"8128b3f2-4bc8-4dd5-bde6-243e28b8f10d\",\"webcompat@mozilla.org\":\"271beea5-2fb0-4a3c-bf8d-aba3d35fce94\",\"default-theme@mozilla.org\":\"3f46493a-5fa7-4a93-b9f2-4e0651e96f00\",\"addons-search-detection@mozilla.com\":\"53090ec6-9e78-4f0a-9d51-a603e6e108da\",\"wikipedia@search.mozilla.org\":\"b2eb0c97-5680-405c-802f-ba509e6583df\",\"ddg@search.mozilla.org\":\"145e535f-c3b6-452e-bd9b-917256328e86\",\"{7c7f5097-d453-4951-8638-d1055726a76b}\":\"f5e0b829-ed51-4129-9ff3-82af94702fee\",\"uBlock0@raymondhill.net\":\"44b9d00a-0265-4210-b415-d485e9cd4243\",\"{446900e4-71c2-419f-a6a7-df9c091e268b}\":\"235a8510-7de1-4ae9-b7ea-5b89bf6d53cd\",\"https-everywhere@eff.org\":\"6d237e92-72fa-4cac-b169-669ee56a7729\",\"jid1-MnnxcxisBPnSXQ@jetpack\":\"404951d0-5d70-4ff9-b769-67a641955c3f\",\"CanvasBlocker@kkapsner.de\":\"bae71db8-4e27-4489-b44a-4abd431c2134\",\"addon@darkreader.org\":\"d6dc9e54-e026-4b0f-b623-b21ff41b92bc\",\"{5b1a796b-231a-4ad1-84ff-918db0818207}\":\"bd00e8c6-2f58-448c-9a41-4409ee652380\",\"extension@tabliss.io\":\"ccf74df9-8299-488e-ae58-946603fd20ce\",\"{2f51855f-5b7f-42f8-83f6-fa3ecacdf08e}\":\"2fec6a48-3954-4b01-bc94-5b9c911f189a\"}");
user_pref("fission.experiment.max-origins.last-disqualified", 0);
user_pref("fission.experiment.max-origins.last-qualified", 1652375046);
user_pref("fission.experiment.max-origins.qualified", true);
user_pref("gfx.blacklist.webrender", 4);
user_pref("gfx.blacklist.webrender.failureid", "FEATURE_FAILURE_DDX_INTEL");
user_pref("intl.accept_languages", "en-US, en");
user_pref("javascript.use_us_english_locale", true);
user_pref("media.gmp-manager.buildID", "20220210135346");
user_pref("media.gmp-manager.lastCheck", 1652374975);
user_pref("media.gmp.storage.version.observed", 1);
user_pref("network.cookie.cookieBehavior", 1);
user_pref("network.http.referer.disallowCrossSiteRelaxingDefault", true);
user_pref("pdfjs.enabledCache.state", true);
user_pref("pdfjs.migrationVersion", 2);
user_pref("pref.general.disable_button.default_browser", false);
user_pref("privacy.annotate_channels.strict_list.enabled", true);
user_pref("privacy.donottrackheader.enabled", true);
user_pref("privacy.history.custom", true);
user_pref("privacy.partition.network_state.ocsp_cache", true);
user_pref("privacy.sanitize.pending", "[]");
user_pref("privacy.trackingprotection.enabled", true);
user_pref("privacy.trackingprotection.socialtracking.enabled", true);
user_pref("privacy.userContext.extension", "CanvasBlocker@kkapsner.de");
user_pref("security.sandbox.content.tempDirSuffix", "6366a53b-7a93-4625-a335-0a2cb550e6c4");
user_pref("toolkit.startup.last_success", 1652374934);
user_pref("toolkit.telemetry.cachedClientID", "54ebff5e-84f0-4136-850e-5ea2b6ff7276");
